### ISSUE TITLE
Enterprise Icon request! 

### ISSUE THREAD

**Issue by stephlao** [telus/tds-core#1261]
Hello! 
we are planning to segment the business website into 2 options for users,
small business and medium & large business! 

we need a custom icon to explain the medium/large business and we were thinking of 2 buildings side by side. 

here is the invision link, the icon will need to be modified (please and thanks christinaaaaa) 
its 2 building icons side by side, one being a bit smaller! 

https://telus.invisionapp.com/share/BKTSC8UYZ96#/383458239_modal_Dialogue_Desktop_2

[](url)

## Actions

1. Did you check to see if there are icons available in TDS that can be used instead? Yes/No
2. Is your proposed icon from the TELUS Brand-approved set from one of the appointed designers*? Yes/No
3. Has your Design Lead or Art Director approved the proposed icon? Yes/No

**1. not available!
2. approved!
3. approved!**

## Guidelines

Icon name: ... 

Usage criteria: ...

**Comment by stephlao** [comment]
SVG has been sent to @Christina-Lo 
github won't let me upload SVG files :(

**Comment by varunj90** [comment]
hey @stephlao can you please tell us who the approvers are?

**Comment by stephlao** [comment]
@varunj90  doug has approved of the design and i've passed it by gary!

**Comment by varunj90** [comment]
thanks @stephlao we'll prioritize this as soon as @gkychow approves.

**Comment by Christina-Lo** [comment]
Have worked with @stephlao and @gkychow for an approved icon. Since SVG's can't be attached, the screen cap below shows what we are moving forward with
<img width="153" alt="Screen Shot 2019-09-18 at 3 41 50 PM" src="https://user-images.githubusercontent.com/42220619/65180495-ff680700-da2a-11e9-9310-fd80c7b6ab39.png">

**Comment by Christina-Lo** [comment]
Worked with @gkychow and @stephlao to work on an approved icon for medium/large. Since github can't upload SVG, screenshot is attached below
<img width="338" alt="Screen Shot 2019-09-18 at 4 10 30 PM" src="https://user-images.githubusercontent.com/42220619/65182289-00029c80-da2f-11e9-9a9f-8bae8ed2bfac.png">

**Comment by varunj90** [comment]
Thanks @Christina-Lo 

@stephlao TDS team will be working on this tomorrow and will release next week.

**Comment by stephlao** [comment]
@varunj90 @Christina-Lo  thank you very much for the quick turnaround! my team and I super appreciate it <3

**Comment by theetrain** [comment]
This has been released in [@tds/core-decorative-icon@2.3.0](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-decorative-icon%402.3.0)!
