### ISSUE TITLE
[UI] Dismissible Notification close button overlaps with text in mobile viewport

### ISSUE THREAD

**Issue by vkyt** [telus/tds-core#1335]
## Description
- on responsive view (mobile), the close button is overlapping with text when content wraps.
## Reproduction Steps
1. View the `dismissible notification` component with text wrap

## Meta

- TDS component version: "@tds/core-notification": "^3.0.7"
- High impact: No 

## Screenshots
![f2e2c20c-78f5-496d-a452-20762fc1bda5](https://user-images.githubusercontent.com/5015168/70255678-2ba34200-1755-11ea-8be3-4ec9cf63baec.png)

**Comment by theetrain** [comment]
I've confirmed there is a padding issue. There should be a 56px space from the right side of the Notification edge to the right side of the Notification copy, in order to provide enough room for the close button. It appears FlexGrid's percentage-based width in the parent wrapper is affecting that space.

**Comment by jraff** [comment]
@vkyt Fixed with [@tds/core-notification@3.0.11](https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-notification%403.0.11)
