### ISSUE TITLE
Inline loader

### ISSUE THREAD

**Issue by thiveyamuthu** [telus/tds-core#1400]
## Description

- Sometimes small detailed information in line that are being fetched from API takes response time and we need a way to let end user know that the information is being loaded.

## Recommendation

- Have a inline loader component that can we used in sentence or in line

## Designs

While loading
![image](https://user-images.githubusercontent.com/58269575/75058232-963c6200-54a8-11ea-820f-0589028782d4.png)

After loading 
![image](https://user-images.githubusercontent.com/58269575/75058488-12cf4080-54a9-11ea-98a5-769f9630b417.png)

## Meta

- TDS component: 
- Willing to develop solution: No
- Has workaround: No 
- High impact: No
- Designer/Developer Pair: Thiveya Muthu and Ruchi Jain

**Comment by donnavitan** [comment]
Related request via Slack "[Changing icon when loading](https://telusdigital.slack.com/archives/C2WK9TP5F/p1579104873011600?thread_ts=1560887107.036000&cid=C2WK9TP5F)"

![image](https://user-images.githubusercontent.com/21316148/75558256-8aecb780-5a0f-11ea-93a9-a493ee5d6fb0.png)
![image](https://user-images.githubusercontent.com/21316148/75558272-917b2f00-5a0f-11ea-8548-dc306771512e.png)

**Comment by donnavitan** [comment]
Hello Thiveya,

Could you please provide the user flow for this? Please include the following:

1. User lands on the page? What does the location empty state look like?
2. User selects a different location? How does the user select this?
3. What does the page look like after they have selected the new location?
4. Why is the location information not available after fetching the location selection?

After some discussion with the team and CX, we'd like some clarification on the need to necessitate loading info at the inline content level. By providing this information, CX is able to better determine if this is a user flow experience or pattern that should be reusable versus providing an alternative selection/loading pattern.

Thank you for your patience!

**Comment by ruchijn** [comment]
Hi Donna,

Below is the scenario when we show the spinner on config. Nothing happens on page load. User selects a device (red box), offers(orange box), plans (purple box) and then we load the summary section (blue box) [Refer full_config_page screenshot]. 

![full_config_page](https://user-images.githubusercontent.com/18288628/75931221-714dd480-5e42-11ea-9a47-4611abc2ed4d.png)


Once summary loads, user sees reserve in store option. 

<img width="570" alt="Screen Shot 2020-03-04 at 5 53 16 PM" src="https://user-images.githubusercontent.com/18288628/75930958-c4735780-5e41-11ea-8d03-79dcdb327f33.png">

This is the default state for that block. Once user uses `Find a store` functionality, we make an API call to get the inventory. And at this point of time we show the spinner as below:

<img width="563" alt="Screen Shot 2020-03-04 at 5 51 54 PM" src="https://user-images.githubusercontent.com/18288628/75931011-e7057080-5e41-11ea-9d0c-7ec7cb1bbdbb.png">

Once API call is done, we show them below screen: 
<img width="568" alt="Screen Shot 2020-03-04 at 5 52 05 PM" src="https://user-images.githubusercontent.com/18288628/75931031-fa184080-5e41-11ea-82c4-576075e95b4d.png">


If you see in the screenshot for spinner, the spacing between `Loading` and `inventory information...` seems to be big. This is due to the `width` and `height` assigned to `svg` tag. 

Hope that helps. If you or anyone else wants to see it in action, I will be more than happy to walk through the steps. 

Please let me know if you need any further info.

**Comment by kittybourne** [comment]
@ruchijn when you click on "Find a store" does a modal appear? How does the customer select the store? If there is a modal, then the spinner should appear in the modal rather than inline after selecting the store.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
