### ISSUE TITLE
Warning: Failed prop type: Invalid prop `reactRouterLinkComponent` of type `object` supplied

### ISSUE THREAD

**Issue by slawler-telus** [telus/tds-core#1401]
## Description

- Link, ButtonLink and ChevronLink all produce warnings when using `reactRouterLinkComponent`.
`VM2549:1 Warning: Failed prop type: Invalid prop `reactRouterLinkComponent` of type `object` supplied to `Link`, expected `function`.`

## Reproduction Steps

```
          import ButtonLink from '@tds/core-button-link'
          import { Link as ReactRouterLink } from 'react-router-dom'

          <ButtonLink
            variant={"primary"}
            target={"_self"}
            to={"/my-app"}
            reactRouterLinkComponent={ReactRouterLink}
          >
            {children}
          </ButtonLink>
```

## Workaround details

Ignore errors

## Meta

- core-chevron-link: v2.1.8
- core-button-link: v2.1.10
- core-link: v2.1.3
- react-router-dom: v5.0.0
- Our code: https://github.com/telus/my-telus-rewards/blob/staging/app/src/ui/components/MultiLink/index.jsx#L148
- Willing to develop solution: Yes/No

## Screenshots
![image](https://user-images.githubusercontent.com/42187593/75188132-70a99580-5700-11ea-9f88-960d39bf5c87.png)
![image](https://user-images.githubusercontent.com/42187593/75188198-8ae37380-5700-11ea-8e01-aa4ee980c5cb.png)
![image](https://user-images.githubusercontent.com/42187593/75188214-946cdb80-5700-11ea-8a6f-1664802b3532.png)
![image](https://user-images.githubusercontent.com/42187593/75188229-99ca2600-5700-11ea-9037-defbcfa6bea0.png)

**Comment by jraff** [comment]
This issue is due to the `Link` component in `react-router` v5 now exporting as a [`forwardRef`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L74). 

Our previous propType check was a `PropTypes.func` which works for all components except those that use `forwardRef`. `forwardRef` still creates a component but in the form of an object as pointed out in this PR. https://github.com/facebook/prop-types/pull/211. We could look to implement this new proptype but that would require us to update all `prop-types` to [v15.7.0](https://github.com/facebook/prop-types/blob/master/CHANGELOG.md).  Resulting in something like this

```
reactRouterLinkComponent: PropTypes.elementType,
```

The option would be to not upgrade `prop-types` and change the current proptype to 
```
reactRouterLinkComponent: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
```

**Comment by marcod1419** [comment]
This issue has been resolved in the newest releases of `Link`, ` ChevronLink`, `ButtonLink` and `Breadcrumbs`.

**Release notes:**
- https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-link%402.2.5 
- https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-chevron-link%402.1.15 
- https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-button-link%402.1.15 
- https://github.com/telus/tds-core/releases/tag/%40tds%2Fcore-breadcrumbs%402.2.2

Thanks for reporting!
