### ISSUE TITLE
Needed: inverted green icons

### ISSUE THREAD

**Issue by dianavolt** [telus/tds-core#1440]
## Description

- Trying to make a IconButtons Add and Subtract more prevalent on the page and to allow for inactive functionality by providing a clear color difference between an active IconButton and an inactive one when values cannot be Subtracted below zero.

## Recommendation

- Inverted green variant needed for icons where action (eg. time) is available. 

## Designs
![image](https://user-images.githubusercontent.com/34690408/80250073-e7dba700-8627-11ea-88d8-9d975b9f0be5.png)

## Meta

- TDS component: IconButton
- Willing to develop solution: Yes
- Has workaround: Yes -- use TDS Core DSM library to modify icon SVG as per need
- High impact: No
- Designer/Developer Pair: Steve Campbell (designer)/Diana Voltchok (dev)

**Comment by theetrain** [comment]
@gkychow will follow up with a path forward.

**Comment by gkychow** [comment]
Hi @dianavolt, sorry for the delay in replying. I've chatted w/ some of our design leads and AADs about this and we feel that for this use-case, it'd be best to go w/ drop-downs to decrease the amount of clicks that a user would need to do to get the quantity that they want. 

From a visual perspective, having the "+" and "-" either filled-in green or stroked would make it harder to visually separate the "hours" and "minutes" fields in each row because of how close all the fields are to each other.

**Comment by dianavolt** [comment]
@gkychow good ideas. We will be moving towards creating a time picker drop down component. So we might have one for your consideration soon :)

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
