### ISSUE TITLE
Ensures [role='img'] elements have alternate text

### ISSUE THREAD

**Issue by dikshaa001** [telus/tds-core#1524]
## Description

- [role='img'] elements should have alternate text

## Reproduction Steps

- Open app in chrome
- install 'axe' accessibility testing extension
- Open sticky footer on the page
- Now click axe in dev tools
- Click 'Scan All Of My Page'
- Observe the error 'Ensures [role='img'] elements have alternate text'

Please see the screenshot atached 
![image](https://user-images.githubusercontent.com/77004851/108205319-ea753300-714a-11eb-9e8c-bdd7c28688ba.png)

## Reproduction Percentage

- 10/10 times

**Comment by nadaltelus** [comment]
@dikshaa001 do you know if this is an issue on TDS or on the implementation of the component?
Can you share which page this issue was found and which component presented it?

tks

The current image component has the property alternate text
![image](https://user-images.githubusercontent.com/101351850/177411178-2777b8aa-01ce-4554-a084-c38dbe58c1b2.png)
