### ISSUE TITLE
Remove safeRest from components

### ISSUE THREAD

**Issue by kyletsang** [telus/tds-core#1593]
## Description

I'd like to be able to style tds core components directly either via `style`, `className`, or styled component's `styled(Component)`.  Currently this isn't possible because `safeRest` strips out `style`/`className` etc.  This would help to reduce number of elements required to create our pages.

## Recommendation

Remove `safeRest`

## Designs

n/a

## Meta

- TDS component: All components
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No

**Comment by billtelus** [comment]
Hi @kyletsang.

This is by design. TDS components block off all customizations as that would break design consistency.
We’re open to changes in any components when justified. You can reach out to us and provide a case for when a component doesn’t fulfill your team’s needs, and we’ll work together to enhance it.
