### ISSUE TITLE
[Button] Id and Value attribute passed to button does not exist in event listener

### ISSUE THREAD

**Issue by marckuo** [telus/tds-core#662]
## Description

* When an id and value attribute is passed to the _button_ component, it shows up in the html element but id is empty string and value is undefined when captured in an event from a click handler

## Reproduction Steps

* Create a button component with an id and value attribute
* Create a click handler function that takes in event as a param
* Console log e.target.id and e.target.value

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: v1.0.1
* Willing to develop solution: Maybe
* Has workaround: No
* High impact: Yes

**Comment by jraff** [comment]
The issue has to do with `event.target` and the way we've built `<Button />`.

**event.target**
> A reference to the object that dispatched the event. It is different from event.currentTarget when the event handler is called during the bubbling or capturing phase of the event.

Our current implementation of `<Button />` looks something like this:

```
<BaseButton onClick={handler}>
  <FlexBox>
    {children}
 </FlexBox>
</BaseButton>
```

In most cases our event is triggered onClick of the `<FlexBox />` and bubbles up to the event handler on `<BaseButton />`. Because `event.target` refers to the originator of the event. (i.e. `<FlexBox />`, **id** and **value** will not exist. You can see `event.target` referring to the `<BaseButton />` when you click on the edges of button, outside of the `<FlexBox />`

<img width="1363" alt="screen shot 2018-07-17 at 3 25 00 pm" src="https://user-images.githubusercontent.com/1036187/42840921-60276c44-89d6-11e8-8da2-92b69e48db22.png">

Another workaround is to use `event.currentTarget`

**event.currentTarget**
> Identifies the current target for the event, as the event traverses the DOM. It always refers to the element to which the event handler has been attached, as opposed to event.target which identifies the element on which the event occurred.
