### ISSUE TITLE
Decibel Partial Masking PII data requires certain TDS Components to accept Node instead of string

### ISSUE THREAD

**Issue by invalidred** [telus/tds-core#781]
## Description

To achieve pro-active Decibel Partial Masking of PII data (though i really wish we achieved this reactively using decibel tools), we need to pass text that contains html such as `<span data-di-mask>`. Here is an example from [decibel docs](https://telusdigital.atlassian.net/wiki/spaces/AI/pages/580517912/How+to+Implement+PII+Blocking)

```
  <h1>Welcome <span data-di-mask>(416)224-8</span>889</h1>
```

## Recommendation

I've identified TDS core components that are PII Partial Masking friendly as they accept `node` as their propType. However there are some other components that will need to accept `node` in order to achieve partial masking.

### Current Components that support PII partial masking

| Component | Prop | Type |
| --- | --- | --- |
|Text | children | PropTypes.node |
| Heading | children | PropTypes.node |
| Paragraph | children | PropTypes.node |
| Link | children | PropTypes.node |
| Notification | children | PropTypes.node |
| UnorderedList | ListItem | PropTypes.node |
| OrderedList | ListItem | PropTypes.node |
| Checkbox | label | PropTypes.node |
| Radio | label | PropTypes.node |
| InputFeedback | children | PropTypes.node |
| Tooltip | children | PropTypes.node |
| Strong | children | PropTypes.node |

### Current Components that *DO NOT* support PII partial masking

| Component | Prop | Type |
| --- | --- | --- |
| ExpandCollapse.Panel | header | PropTypes.string |
| Input | label | PropTypes.string |
| Select | option.text | PropTypes.string |
| Select | placeholder | PropTypes.string |
| TextArea | label | PropTypes.string |
| Small | children | PropTypes.string |

## Meta

- TDS version: current
- Willing to develop solution: Do not mind giving my 2 cents.
- Has workaround: Yes (Do not support partial masking of PII, completely block PII)
- High impact: Not sure (Depends of business needs)
- Designer/Developer Pair: N/A, Abdul Khan

**Comment by simpleimpulse** [comment]
Talked to @invalidred about this and there are a few potential solutions to consider:

- Modify the unsupported components to accept nodes instead of strings. This needs careful consideration and we have to validate why these components were restricted to strings in the first place and what other externalities this may cause.
- Create a TDS component which will wrap any PII and can be used with decibel or other alternatives if needed in the future. This seems like a better, more elegant solution that isn't tied down to decibel.

This should be taken to Tech Forum to get input from the rest of our community.

**Comment by nadaltelus** [comment]
Closing the issue due to lack of activity. If surfaced again, will consider as input for the new DS.
