### ISSUE TITLE
Same font for notification texts

### ISSUE THREAD

**Issue by Mariefhrmnn** [telus/tds-core#937]
## Description

We have different type of notification status in TSD library: branded, default, dismiss, error, success…
But some of them use Helvetica Neue light font and some of them Helvetica Neue medium font. 

## Recommendation

To have a best logic and uniformisation to use these notifications, I recomment to have just one type of font for these notification blocks. 
So the solution that I propose is to use always the Helvetica Neue light font and if we want to accentuate/ give more importance to a term we will use Helvetica Neue medium font.

## Designs

**Current design**
Branded notification: 
![screen shot 2019-02-13 at 4 28 18 pm](https://user-images.githubusercontent.com/44266628/52746488-9fe6dc00-2faf-11e9-84a2-e4857bd6a2cf.png)

**Current and Improved design**
Success notification: 
![screen shot 2019-02-13 at 4 28 29 pm](https://user-images.githubusercontent.com/44266628/52746596-e0465a00-2faf-11e9-906a-365968545b9b.png)
![screen shot 2019-02-13 at 4 52 16 pm](https://user-images.githubusercontent.com/44266628/52746600-e2a8b400-2faf-11e9-9923-9c77e9863e78.png)

**Current and Improved design**
Error notification:
![screen shot 2019-02-13 at 4 28 50 pm](https://user-images.githubusercontent.com/44266628/52746606-e6d4d180-2faf-11e9-8ffa-3ffc65041b0f.png)
![screen shot 2019-02-13 at 4 28 58 pm](https://user-images.githubusercontent.com/44266628/52746609-e9cfc200-2faf-11e9-8fc6-cf75a0d46964.png)

## Meta

- TDS component: Version: 1.2.9
- Willing to develop solution: Yes
- Has workaround: No
- High impact: No 
- Designer/Developer Pair: Marie Fuhrmann / @Berjesty and @invalidred / @Jeffrey-Chang / @jesdavpet

**Comment by Christina-Lo** [comment]
As mentioned in the TDS-Guild thread on Feb 14, 2019 this is already something that is doable. 
_You may use text-based styling such as bold text or links. Do not use other complex components or_ paragraphs. Find more examples here: https://tds.telus.com/components/index.html#notification

It is up to the designers/content writers to determine what kind of information should be called out and we should only be bolding the most important part of the message. It’ll be too hard to read if the whole message was bolded.

**Comment by Jeffrey-Chang** [comment]
Our team is currently using `Contentful`. One thing about mid sentence *bolding* is that it is very code and/or `Contentful` bloating.

We aren’t just able to use something like `Random text <Text bold>bold text</Text> more random text` through `Contentful`. It just comes back as a `string` and non converted `React`/`HTML`.

Due to that, we would either have to create 3 separate entries in `Contentful`, get the entries and then do something like `<Text>{contentful.randomText} <Text bold>{contentful.boldText} </Text> {contenful.otherRandomText}</Text>`

Another possible way would be to put something like a flag in the `Contentful` entry (e.g “random text {BOLD_TEXT_GOES_HERE} other random text”) and then take that string, split it, insert the `TDS` component, join the sentence and then display it.

I’ve also heard of other teams doing stuff like `<b dangerouslySetInnerHTML={CONTENTFUL_ENTRY} className="bold-text" />` and then doing some custom CSS to match how TDS looks

**Comment by donnavitan** [comment]
As per discussion with TDS and CX/design direction we'll proceed with the following enhancements to notifications:
* Allow for the ability to use regular (Helvetica light) and bold (Helvetica medium) text for all notifications
* Success and error notifications that are currently in the wild must maintain their current bold state - so as to not require additional effort to manually change them to bold; can still allow use of regular/bold

Please proceed and let us know if you need further help/direction. Thank you!

**Comment by Mariefhrmnn** [comment]
Hey @varunj90 
Will the TDS team be adding the enhancement to notifications component as outlined above by @donnavitan?

**Comment by varunj90** [comment]
yes @Mariefhrmnn , TDS team is prioritizing this issue

**Comment by jraff** [comment]
@Mariefhrmnn This has been fixed with `@tds/core-notification@1.2.34`. Thanks for reporting this issue!
